spring.application.name=UltraVExpotech
# Configuração da conexão com o MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ultrav?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# Configurações do Hibernate / JPA
# Força o Hibernate a criar as tabelas baseadas nas suas classes Java toda vez que iniciar
spring.jpa.hibernate.ddl-auto=update

# Isso mostrará no console do IntelliJ exatamente qual query ele está tentando rodar
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
